pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Building the application..."
                dir('07-jenkins/') {
                sh "docker build -t ppr88/devops-bootcamp-module08:1.0 ."
                }
            }
        }
        stage('Test') {
            steps {
                echo "Testing the application..."
                dir('07-jenkins/') {
                    sh "docker run node_app npm test"
                }
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying the application..."
                dir('07-jenkins/') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        echo "${env.PASS}"
                        sh "echo ${PASS} | docker login -u ${USER} --password-stdin"
                        sh "docker push ppr88/devops-bootcamp-module08:1.0"
                    }
                } 
            }
        }
    }
}