pipeline {
    agent any

    stages {
        stage('Bump version') {
            steps {
                echo "Bumping the application version..."
                dir('07-jenkins/app/') {
                    script {
                        // Bump version in package.json, capture and format the new application version 
                        env.APP_VERSION = sh(script: "npm version patch", returnStdout: true).trim()
                        env.APP_VERSION = "${env.APP_VERSION.substring(1)}-${env.BUILD_NUMBER}"
                    }
                    echo "new app version is: ${env.APP_VERSION}"
                }
            }
        }
        stage('Build') {
            steps {
                echo "Building the application..."
                dir('07-jenkins/') {
                    sh "docker build -t ppr88/devops-bootcamp-module08:${env.APP_VERSION} ."
                }
            }
        }
        stage('Test') {
            steps {
                echo "Testing the application..."
                dir('07-jenkins/') {
                    sh "docker run node_app npm test"
                }
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying the application..."
                dir('07-jenkins/') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh "echo '${env.PASS}' | docker login -u '${env.USER}' --password-stdin"
                        sh "docker push ppr88/devops-bootcamp-module08:${env.APP_VERSION}"
                    }
                } 
            }
        }
    }
}