version: "3"
services:
    mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
        - MYSQL_DATABASE=mydb
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=${MYSQL_PWD}

    phpmyadmin:
        image: phpmyadmin
        ports:
          - "8081:80"
        environment:
          - PMA_HOST=mysql
          - PMA_PORT=3306
        restart: always
        depends_on:
          - mysql

    java-app:
      image: java-app:1
      ports:
        - "8080:8080"
      environment:
        - DB_NAME=mydb
        - DB_SERVER=mysql
        - DB_USER=admin
        - DB_PWD=${MYSQL_PWD}
      restart: always
      depends_on:
        - mysql