#!/usr/bin/env groovy

library identifier: 'jenkins-shared-library@master', retriever: modernSCM(
    [$class: 'GitSCMSource',
    remote: 'https://gitlab.com/twn-devops-bootcamp/latest/09-aws/jenkins-shared-library.git',
    credentialsID: 'gitlab-credentials'
    ]
)

pipeline {
    agent any
    tools {
        maven 'maven-3.9'
    }
    environment {
        IMAGE_NAME = 'ppr88/devops-bootcamp-module08:java-maven-1.0'
    }
    stages {
        stage('build app') {
            steps {
                echo 'building application jar...'
                dir('08-aws/') {
                    buildJar()
                }
            }
        }
        stage('build image') {
            steps {
                dir('08-aws/') {
                    script {
                        echo 'building the docker image...'
                        buildImage(env.IMAGE_NAME)
                        dockerLogin()
                        dockerPush(env.IMAGE_NAME)
                    }
                }
            }
        } 
        stage("deploy") {
            steps {
                script {
                    echo 'deploying docker image to EC2...'
                    def dockerComposeCmd = "docker-compose -f docker-compose.yaml up --detach"
                    sshagent(['ec2-key']) {
                        sh "scp 08-aws/docker-compose.yaml ec2-user@35.180.196.85:/home/ec2-user"
                        sh "ssh -o StrictHostKeyChecking=no ec2-user@35.180.196.85 ${dockerComposeCmd}"
                    }
                }
            }               
        }
    }
}
